os:
  - linux
#  - windows
language: python
jobs:
  include:
    - python: "3.6"
      env: NETWORKX_VERSION=2.0
    - python: "3.7"
      env: NETWORKX_VERSION=2.1
    - python: "3.8"
      env: NETWORKX_VERSION=2.2
    - python: "3.8"
      env: NETWORKX_VERSION=2.3
    - python: "3.9"
      env: NETWORKX_VERSION=2.5
install:
  - pip install -r requirements-travis.txt
script:
  - pytest
